# Generated by Django 4.1.2 on 2022-10-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('to', models.CharField(choices=[('non', ''), ('btgl', 'bosaso to galkacyo'), ('btg', 'bosaso to garowe'), ('btq', 'bosaso to qardho'), ('btl', 'bosaso to lascano')], default='non', max_length=255)),
                ('date', models.DateField(auto_now_add=True, verbose_name='create at')),
                ('total', models.CharField(max_length=50)),
            ],
        ),
    ]
