# Generated by Django 4.1.2 on 2023-01-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('to', models.CharField(choices=[('bosaso to galkacyo', 'btgl'), ('bosaso to qardho', 'btq'), ('non', 'non'), ('bosaso to lascano', 'btl'), ('bosaso to garowe', 'btg')], default='non', max_length=255, verbose_name='toto')),
                ('date', models.DateField(auto_now_add=True)),
                ('go_date', models.DateField()),
                ('cost', models.CharField(default=[], max_length=255)),
            ],
        ),
    ]
