# Generated by Django 4.1.2 on 2022-10-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('to', models.CharField(choices=[('bosaso to garowe', 'btg'), ('non', ''), ('bosaso to lascano', 'btl'), ('bosaso to qardho', 'btq'), ('bosaso to galkacyo', 'btgl')], default='non', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('go_date', models.DateField(blank=True, null=True)),
                ('total', models.CharField(default='00', max_length=50)),
            ],
        ),
    ]
