# Generated by Django 4.1.2 on 2022-10-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='to',
            field=models.CharField(choices=[('btg', 'bosaso to garowe'), ('btl', 'bosaso to lascano'), ('non', ''), ('btq', 'bosaso to qardho'), ('btgl', 'bosaso to galkacyo')], default='non', max_length=255),
        ),
    ]
