# Generated by Django 4.1.2 on 2022-10-28 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='go_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='to',
            field=models.CharField(choices=[('bosaso to lascano', 'btl'), ('bosaso to garowe', 'btg'), ('bosaso to galkacyo', 'btgl'), ('non', ''), ('bosaso to qardho', 'btq')], default='non', max_length=255),
        ),
    ]
