# Generated by Django 4.1.2 on 2022-10-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ticketmodel_go_date_alter_ticketmodel_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='to',
            field=models.CharField(choices=[('non', 'non'), ('bosaso to qardho', 'btq'), ('bosaso to galkacyo', 'btgl'), ('bosaso to garowe', 'btg'), ('bosaso to lascano', 'btl')], default='non', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='total',
            field=models.CharField(max_length=50),
        ),
    ]
