# Generated by Django 4.1.2 on 2022-10-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ticketmodel_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='to',
            field=models.CharField(choices=[('btgl', 'bosaso to galkacyo'), ('btq', 'bosaso to qardho'), ('non', ''), ('btl', 'bosaso to lascano'), ('btg', 'bosaso to garowe')], default='non', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='total',
            field=models.CharField(default='00', max_length=50),
        ),
    ]
