# Generated by Django 4.1.2 on 2022-10-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ticketmodel_date_alter_ticketmodel_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='to',
            field=models.CharField(choices=[('non', ''), ('bosaso to qardho', 'btq'), ('bosaso to lascano', 'btl'), ('bosaso to garowe', 'btg'), ('bosaso to galkacyo', 'btgl')], default='non', max_length=255, verbose_name='to'),
        ),
    ]
