# Generated by Django 4.1.2 on 2023-01-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ticketmodel_cost_alter_ticketmodel_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='to',
            field=models.CharField(choices=[('bosaso to garowe', 'btg'), ('bosaso to qardho', 'btq'), ('bosaso to lascano', 'btl'), ('non', 'non'), ('bosaso to galkacyo', 'btgl')], default='non', max_length=255, verbose_name='toto'),
        ),
    ]
