# Generated by Django 4.1.2 on 2022-10-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ticketmodel_to_alter_ticketmodel_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='total',
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='to',
            field=models.CharField(choices=[('non', 'non'), ('bosaso to qardho', 'btq'), ('bosaso to garowe', 'btg'), ('bosaso to lascano', 'btl'), ('bosaso to galkacyo', 'btgl')], default='non', max_length=255, verbose_name='toto'),
        ),
    ]
