# Generated by Django 4.1.2 on 2022-10-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ticketmodel_total_alter_ticketmodel_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='cost',
            field=models.CharField(default=[], max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='to',
            field=models.CharField(choices=[('bosaso to galkacyo', 'btgl'), ('bosaso to qardho', 'btq'), ('bosaso to lascano', 'btl'), ('non', 'non'), ('bosaso to garowe', 'btg')], default='non', max_length=255, verbose_name='toto'),
        ),
    ]
